config/routes.rb
Rails.application.routes.draw do

  #get '/tasks/index'
    
  #get 'show' =>'tasks#show'
  # get 'tasks#show', as: 'show'

  resources :projects do
    resources :tasks
  end

  # get '/tasks:id', to: 'tasks#show'
  #resources :projects

  #root to: 'tasks#index'
  #root 'tasks#index', as: 'home'

  root 'projects#index', as: 'home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ApplicationRecord
  has_many :tasks
  validates :name, presence: true, length: {minimum:3, maximum:20}
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :project 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
 # http_basic_authenticate_with name: 'asd', password: 'sda', except: [ :index, :show ]
  # layout false
  #layout "app" 


  def index 
    @projects = Project.all
  end
 
  def show
    @project = Project.find(params[:id])
  end 

  def new
    @project = Project.new
  end


  def edit
    @project = Project.find(params[:id])
  end

  def update
    @project = Project.find(params[:id])

    if(@project.update(project_params))
      redirect_to projects_path
    else  
      render 'edit'
    end 
  end
  
 
  def create 
    @project = Project.new(project_params)
    if(@project.save)
      redirect_to @project
    else  
      render 'new'
    end 
  end
 

  def destroy
    @project = Project.find(params[:id])
    @project.destroy

    redirect_to projects_path
  end

  private
    def project_params
      params.require(:project).permit(:name, :status=>'0') 
    end 

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
    def create
      @project = Project.find(params[:project_id])
      @task = @project.tasks.create(task_params)

      redirect_to project_path(@)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/app.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tasker</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>


    <!-- <h1><%#= tasks_index_path%></h1> -->

    <%= yield :nav %>
    
     <%#= render '/layouts/partials/header.html.erb' %>
     <%#= render :partial => "/partial/header.html.erb" %>
    <div class="container">
      <%= yield  %>
      <%= yield :content %>
    </div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tasker</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/nav.html.erb
<% content_for :nav do %>

  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="#">Home 2<span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Dropdown
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="#">Action</a>
            <a class="dropdown-item" href="#">Another action</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#">Something else here</a>
          </div>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
        </li>
      </ul>
      <form class="form-inline my-2 my-lg-0">
        <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
      </form>
    </div>
  </nav> 

 <% end %>

app/views/layouts/partials/_header.html.erb
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="/">Home</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active"> 
          <%#= link_to 'Show', show_path, class: 'nav-link' %>
          <%#= link_to 'Show', {controller: 'tasks', action: "show"}, class: 'nav-link' %>
        </li>
        <li class="nav-item active"> 
          <%#= link_to 'New2', new_task_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'New', new_project_path, class: 'nav-link' %>
          <%#= link_to 'New', {controller: 'projects', action: "new"}, class: 'nav-link' %>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Dropdown
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="#">Action</a>
            <a class="dropdown-item" href="#">Another action</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#">Something else here</a>
          </div>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
        </li>
      </ul>
      
      <form class="form-inline my-2 my-lg-0">
        <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
      </form>
    </div>
  </nav> 

app/views/projects/edit.html.erb
<h1>edit page</h1>


<div class="form-group"> 
  <%= form_for :project, url: project_path(@project), method: :patch do |f| %>
   
    <%if @project.errors.any? %>
      <% @project.errors.full_messages.each do |msg| %>
        <p class='alert alert-danger'><%= msg %></p>
      <% end %>
    <% end %>

    <div class="form-group">
      <label for="line_1" style = 'text-transform: uppercase;'>edited <%= project_path(@project)%></label>
      <%= f.text_field :name, :class=>"form-control", :id=>"line_1" %>
    </div>
    <%= f.submit({ :class => 'btn btn-primary'}) %>
  <%end%>
</div>

app/views/projects/index.html.erb
 <h1>Projects list</h1>

<% content_for :content do %>
  <div id="app"> 
    <% @projects.each do |i| %> 
      <div class="wrap d-flex align-items-center">
        <a href="<%= project_path(i)%>" class="list-group-item list-group-item-action flex-column align-items-start">
          <div class="d-flex w-100 justify-content-between">
          <h5 class="mb-1"><%= i.name %> </h5>
          <small class="text-muted"><%= i.created_at %> </small>
          </div>
          <small class="text-muted">project_id = <%= i.id%></small>
        </a>
          <%= link_to 'add new', new_project_path, ({:class=>"btn btn-sm btn-outline-info "}) %>
          <%= link_to 'edit', edit_project_path(i), ({:class=>"btn btn-sm btn-outline-info "}) %>
          <%= link_to 'del', project_path(i), method: :delete, data: { confirm: 'Are you sure?' }, :class=>"btn btn-sm btn-outline-info" %>
      </div>
    <% end %>
  </div> 
<% end %>

app/views/projects/new.html.erb
<div class="form-group"> 
  <%= form_for :project, url: projects_path do |f| %>
   
    <%if @project.errors.any? %>
      <% @project.errors.full_messages.each do |msg| %>
        <p class='alert alert-danger'><%= msg %></p>
      <% end %>
    <% end %>

    <div class="form-group">
      <label for="line_1" style = 'text-transform: uppercase;'> <%= projects_path%> </label>
      <%= f.text_field :name, :class=>"form-control", :id=>"line_1" %>
    </div>
    <%= f.submit({ :class => 'btn btn-primary'}) %>
  <%end%>
</div>

app/views/projects/show.html.erb
<h1>Project detailes</h1>

<h2><%= @project.name%></h2> 

 <hr>

  <h1>add new task</h1>
      

<div class="form-group"> 
  <%= form_for([@project, @project.tasks.build]) do |f| %> 
    <div class="form-group">
      <label for="line_1" style = 'text-transform: uppercase;'>name task 2<%= projects_path%>2</label>
      <%= f.text_field :name, :class=>"form-control", :id=>"line_1" %>
    </div>
    <%= f.submit({ :class => 'btn btn-primary'}) %>
  <%end%>
</div>

app/views/tasks/edit.html.erb
<h1>edit page</h1>


<div class="form-group"> 
  <%= form_for :task, url: task_path(@task), method: :patch do |f| %>
   
    <%if @task.errors.any? %>
      <% @task.errors.full_messages.each do |msg| %>
        <p class='alert alert-danger'><%= msg %></p>
      <% end %>
    <% end %>

    <div class="form-group">
      <label for="line_1" style = 'text-transform: uppercase;'>edited <%= task_path(@task)%></label>
      <%= f.text_field :name, :class=>"form-control", :id=>"line_1" %>
    </div>
    <%= f.submit({ :class => 'btn btn-primary'}) %>
  <%end%>
</div>

app/views/tasks/index.html.erb
 <h1>Home page</h1>


<% content_for :content do %>
  <div id="app"> 
    <% @all_Project.each do |i| %> 
      <div class="wrap d-flex align-items-center">
        <a href="<%= task_path(i)%>" class="list-group-item list-group-item-action flex-column align-items-start">
          <div class="d-flex w-100 justify-content-between">
          <h5 class="mb-1"><%= i.name %> </h5>
          <small class="text-muted"><%= i.created_at %> </small>
          </div>
          <p class="mb-1">status = <%= i.status%></p>
          <small class="text-muted">project_id = <%= i.project_id%></small>
        </a> 
          <%= link_to 'add new', new_task_path, ({:class=>"btn btn-sm btn-outline-info "}) %>
          <%= link_to 'edit', edit_task_path(i), ({:class=>"btn btn-sm btn-outline-info "}) %>
          <%= link_to 'del', task_path(i), method: :delete, data: { confirm: 'Are you sure?' }, :class=>"btn btn-sm btn-outline-info" %>
      </div>
    <% end %>
  </div> 
<% end %>

app/views/tasks/new.html.erb
<div class="form-group"> 
  <%= form_for :task, url: tasks_path do |f| %>
   
    <%if @task.errors.any? %>
      <% @task.errors.full_messages.each do |msg| %>
        <p class='alert alert-danger'><%= msg %></p>
      <% end %>
    <% end %>

    <div class="form-group">
      <label for="line_1" style = 'text-transform: uppercase;'>name task 2<%= tasks_path%>2</label>
      <%= f.text_field :name, :class=>"form-control", :id=>"line_1" %>
    </div>
    <%= f.submit({ :class => 'btn btn-primary'}) %>
  <%end%>
</div>

app/views/tasks/show.html.erb
<h1>show page</h1>

<h2><%= @task.name%></h2>
<h4><%= @task.status%></h4>

 